name: build_upload_notify
on:
  push:
    branches:
      - master
      - test
      - develop

jobs:
  build_upload_notify:
    name: build_upload_notify
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Get Branch Name
        id: branch
        run: echo ::set-output name=branch::${GITHUB_REF#refs/*/}
      - name: Get Today Date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d-%H:%M:%S')"
      - name: Get Folder ID by condition
        uses: haya14busa/action-cond@v1
        id: folderid
        with:
          cond: ${{ steps.branch.outputs.branch == 'develop' }}
          if_true: ${{ secrets.TESTFOLDERID}}
          if_false: ${{ secrets.MASTERFOLDERID}}
      - run: flutter pub get
      - run: flutter build apk
      - name: Archive Files
        run: |
          sudo apt-get update
          sudo apt-get install zip
          zip -r archive.zip *
      - name: Upload APK to Google Drive
        uses: adityak74/google-drive-upload-git-action@main
        with:
          credentials: ${{ secrets.GSA }}
          filename: "build/app/outputs/flutter-apk/app-release.apk"
          folderId: ${{ steps.folderid.outputs.value }}
          name: ${{ steps.branch.outputs.branch }}_${{ steps.date.outputs.date }}_apk.apk # optional string
          overwrite: "false" # optional boolean
          mimeType: "application/vnd.android-package-archive"


      - name: Upload Deploygate
        uses: minhchienwikipedia/deploygate-upload-app@master
        with:
          app_owner_name: hoangduchuuvn
          api_token: ${{ secrets.DEPLOYGATE_API_TOKEN }}
          app_file_path: "build/app/outputs/flutter-apk/app-release.apk"
          message: Update ${{steps.branch.outputs.branch}} - ${{ steps.date.outputs.date }}

      - name: GET CHANNEL NAME
        uses: haya14busa/action-cond@v1
        id: channel
        with:
          cond: ${{ steps.branch.outputs.branch == 'develop' }}
          if_true: doctor-ui-build-sounder
          if_false: doctor-ui-release

      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: ${{ steps.channel.outputs.value }}
          SLACK_COLOR: ${{ job.status }} # or a specific color like 'good' or '#ff00ff'
          SLACK_ICON: https://github.githubassets.com/images/mona-loading-default.gif
          SLACK_MESSAGE: Above APK uploaded to this folder https://drive.google.com/drive/folders/${{ steps.folderid.outputs.value}}. DeployGate Also uploaded
          SLACK_TITLE: Upload new `${{steps.branch.outputs.branch}}` APK named `${{ steps.branch.outputs.branch }}_${{ steps.date.outputs.date }}_apk.apk`
          SLACK_USERNAME: cái loa phường
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_FOOTER: This message was sent by `Cái Loa`